sudo: false  # Use container-based infrastructure
language: python
python:
  - "2.7"
  - "3.6"
git:
  # don't need the default depth of 50
  # but don't want to use a depth of 1 since that affects
  # whether jobs run when you have multiple commits queued
  # https://github.com/travis-ci/travis-ci/issues/4575
  depth: 10
cache:
  pip: true
  # cache directory used for Ensembl downloads of GTF and FASTA files
  # along with the indexed db of intervals and ID mappings and pickles
  # of sequence dictionaries. Also, pip
  directories:
    - $HOME/miniconda
before_install:
  - |
    if [ -d  $HOME/miniconda/bin ];
      then
      echo "miniconda already installed"
    else
      rm -rf $HOME/miniconda
      if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
        wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
      else
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
      fi
      bash miniconda.sh -b -p $HOME/miniconda
      export PATH="$HOME/miniconda/bin:$PATH"
    fi
  # reset the shell's lookup table for program name to path mappings
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  - python --version
install:
  - >
      conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION
      numpy scipy nose pandas pandoc
  - source activate test-environment
  - pip install pypandoc pylint
  - pip install -r requirements.txt
  - pip install .
  - pip install coveralls
script:
  - ./lint.sh
  - nosetests test --with-coverage --cover-package=pepdata
after_success:
  coveralls
deploy:
  provider: pypi
  user: openvax
  distributions: sdist
  password:
    secure: "adaJvYZ6lDNqhf4jwrI3tsNVymL54yfKl8ymQPUYaL2yK75MaTurfoqqHEt31FXiZNUvwOz+o0i9GHoGRhoVlHKNoe/bN6f69qkNZNW/YC4b061/kPOdzpdpwFzrxXE9Zr6KPsbnGNGcJXzga9rd7XTh8Y34VDylylb5bhYmTC0="
  on:
    branch: master
    condition: $TRAVIS_PYTHON_VERSION = "2.7"
